"""Alex Videos: downloads new videos from fixed YouTube channels."""

import json
import os
import queue
import subprocess
import sys
import threading
import urllib.request

try:
    from _version import VERSION  # generated by the build job
except ImportError:
    VERSION = 0

GITHUB_REPO = "didriksg/alex-download"
CHANNELS_URL = f"https://raw.githubusercontent.com/{GITHUB_REPO}/main/channels.txt"
DEFAULT_CHANNELS = ["https://www.youtube.com/@AlexSkoog-ks1pl"]
FORMAT = "bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best"

FROZEN = getattr(sys, "frozen", False)
APP_DIR = os.path.dirname(sys.executable if FROZEN else os.path.abspath(__file__))


def load_channels():
    local = os.path.join(APP_DIR, "channels.txt")
    text = ""
    try:
        with urllib.request.urlopen(CHANNELS_URL, timeout=5) as r:
            text = r.read().decode("utf-8")
        if FROZEN:  # offline-fallback cache; skipped in dev to keep the repo copy pristine
            try:
                with open(local, "w", encoding="utf-8") as f:
                    f.write(text)
            except OSError:
                pass
    except Exception:
        try:
            with open(local, encoding="utf-8") as f:
                text = f.read()
        except OSError:
            pass
    urls = [s.strip() for s in text.splitlines() if s.strip() and not s.startswith("#")]
    return urls or DEFAULT_CHANNELS


DEST_FILE = os.path.join(APP_DIR, "folder.txt")


def load_choice():
    """Where to save: "pc" (~/Videos) or "usb" (first USB stick)."""
    try:
        with open(DEST_FILE, encoding="utf-8") as f:
            return "usb" if f.read().strip() == "usb" else "pc"
    except OSError:
        return "pc"


def save_choice(choice):
    try:
        with open(DEST_FILE, "w", encoding="utf-8") as f:
            f.write(choice)
    except OSError:
        pass


def find_usb_drives():
    if sys.platform == "win32":
        import ctypes

        k32 = ctypes.windll.kernel32
        bitmask = k32.GetLogicalDrives()
        return [
            f"{chr(65 + i)}:\\"
            for i in range(26)
            if bitmask & (1 << i) and k32.GetDriveTypeW(f"{chr(65 + i)}:\\") == 2
        ]
    # ponytail: macOS branch is dev-only; the end user is on Windows
    return [
        os.path.join("/Volumes", d)
        for d in os.listdir("/Volumes")
        if d != "Macintosh HD"
    ]


def download_new_videos(dest_root, channels, event_cb, cancel=None):
    """Downloads new videos. Sends ("status", text)/("progress", 0..1) to
    event_cb; a set cancel event stops after the current chunk.
    Returns (new_count, all_ok)."""
    import yt_dlp

    videos_dir = dest_root
    os.makedirs(videos_dir, exist_ok=True)
    done_ids = set()

    def hook(d):
        if cancel is not None and cancel.is_set():
            raise yt_dlp.utils.DownloadCancelled("stopped by user")
        info = d.get("info_dict") or {}
        title = info.get("title") or ""
        if d["status"] == "downloading":
            event_cb(("status", f"Laster ned: {title}"))
            total = d.get("total_bytes") or d.get("total_bytes_estimate")
            if total:
                event_cb(("progress", d.get("downloaded_bytes", 0) / total))
        elif d["status"] == "finished":
            if info.get("id"):
                done_ids.add(info["id"])
            event_cb(("status", f"Behandler: {title} ..."))
            event_cb(("progress", 1.0))

    opts = {
        "format": FORMAT,
        "merge_output_format": "mp4",
        "outtmpl": os.path.join(videos_dir, "%(channel)s", "%(title)s.%(ext)s"),
        "download_archive": os.path.join(videos_dir, ".downloaded.txt"),
        "windowsfilenames": True,
        "ignoreerrors": True,
        "retries": 3,
        "quiet": True,
        "no_warnings": True,
        "noprogress": True,
        "progress_hooks": [hook],
    }
    if FROZEN:
        opts["ffmpeg_location"] = sys._MEIPASS
        opts["js_runtimes"] = {"deno": {"path": os.path.join(sys._MEIPASS, "deno.exe")}}

    with yt_dlp.YoutubeDL(opts) as ydl:
        try:
            retcode = ydl.download(channels)
        except yt_dlp.utils.DownloadCancelled:
            return len(done_ids), True
    return len(done_ids), retcode == 0


def check_for_update(event_cb):
    """Swaps the running exe for the newest GitHub release. Returns new path or None."""
    if not FROZEN:
        return None
    exe = sys.executable
    try:
        os.remove(exe + ".old")
    except OSError:
        pass
    new = exe + ".new"
    try:
        url = f"https://api.github.com/repos/{GITHUB_REPO}/releases/latest"
        with urllib.request.urlopen(url, timeout=5) as r:
            rel = json.load(r)
        if int(rel["tag_name"].lstrip("v")) <= VERSION:
            return None
        asset = next(a for a in rel["assets"] if a["name"].endswith(".exe"))
        event_cb(("status", "Laster ned oppdatering ..."))

        def report(blocks, bs, total):
            if total > 0:
                event_cb(("progress", min(blocks * bs / total, 1.0)))

        urllib.request.urlretrieve(asset["browser_download_url"], new, report)
        os.rename(exe, exe + ".old")
        os.rename(new, exe)
        return exe
    except Exception:
        try:
            os.remove(new)
        except OSError:
            pass
        return None


class App:
    def __init__(self, root):
        self.root = root
        self.msgs = queue.Queue()
        self.choice = load_choice()
        self.cancel = threading.Event()
        self.downloading = False
        root.title("Alex Videoer")
        root.geometry("520x420")
        root.resizable(False, False)
        if FROZEN:
            root.iconbitmap(os.path.join(sys._MEIPASS, "icon.ico"))

        ctk.CTkLabel(
            root, text="Alex sine videoer", font=ctk.CTkFont(size=28, weight="bold")
        ).pack(pady=(36, 4))
        ctk.CTkLabel(
            root,
            text="Henter nye videoer fra YouTube",
            font=ctk.CTkFont(size=13),
            text_color="gray60",
        ).pack(pady=(0, 24))
        self.button = ctk.CTkButton(
            root,
            text="Hent nye videoer",
            font=ctk.CTkFont(size=20, weight="bold"),
            height=56,
            corner_radius=28,
            command=self.on_button,
            state="disabled",
        )
        self.button_colors = {
            "fg_color": self.button.cget("fg_color"),
            "hover_color": self.button.cget("hover_color"),
        }
        self.button.pack(fill="x", padx=56)
        self.bar = ctk.CTkProgressBar(root, height=8)
        self.bar.set(0)
        self.bar.pack(fill="x", padx=56, pady=(24, 10))
        self.status = ctk.CTkLabel(root, text="Starter ...", wraplength=440)
        self.status.pack(padx=24)

        bottom = ctk.CTkFrame(root, fg_color="transparent")
        bottom.pack(side="bottom", fill="x", pady=(0, 16))
        ctk.CTkLabel(
            bottom,
            text="Hvor skal videoene lagres?",
            font=ctk.CTkFont(size=12),
            text_color="gray60",
        ).pack()
        self.where = ctk.CTkSegmentedButton(
            bottom,
            values=["På PC-en", "På minnepinne"],
            font=ctk.CTkFont(size=13),
            command=self.choose_where,
        )
        self.where.set("På minnepinne" if self.choice == "usb" else "På PC-en")
        self.where.pack(pady=(4, 12))
        ctk.CTkButton(
            bottom,
            text="Åpne videomappen",
            command=self.open_folder,
            font=ctk.CTkFont(size=13),
            height=32,
            fg_color="gray25",
            hover_color="gray30",
        ).pack()
        root.after(150, self.poll)
        threading.Thread(target=self.update_worker, daemon=True).start()

    def update_worker(self):
        new_exe = check_for_update(self.msgs.put)
        if new_exe:
            self.msgs.put(("status", "Appen er oppdatert og starter på nytt ..."))
            subprocess.Popen([new_exe])
            self.msgs.put(("quit",))
        else:
            self.msgs.put(("ready",))

    def choose_where(self, value):
        self.choice = "usb" if "minnepinne" in value.lower() else "pc"
        save_choice(self.choice)
        if self.choice == "usb" and not find_usb_drives():
            self.status.configure(text="Sett inn minnepinnen før du henter videoer.")
        else:
            self.status.configure(text="Trykk på knappen for å hente nye videoer.")

    def resolve_dest(self):
        """Path to save into, or None if the chosen USB stick is missing."""
        if os.environ.get("ALEX_DEST"):  # dev override so tests stay off ~/Videos
            return os.environ["ALEX_DEST"]
        if self.choice == "usb":
            drives = find_usb_drives()
            # ponytail: first stick wins; add a picker if several sticks becomes real
            return drives[0] if drives else None
        return os.path.join(os.path.expanduser("~"), "Videos")

    def open_folder(self):
        dest = self.resolve_dest()
        if dest is None:
            self.status.configure(text="Fant ingen minnepinne. Sett den inn og prøv igjen.")
            return
        os.makedirs(dest, exist_ok=True)
        if sys.platform == "win32":
            os.startfile(dest)
        else:
            subprocess.run(["open", dest])

    def on_button(self):
        if self.downloading:
            self.cancel.set()
            self.button.configure(state="disabled")
            self.status.configure(text="Stopper ...")
        else:
            self.start()

    def start(self):
        dest = self.resolve_dest()
        if dest is None:
            self.status.configure(text="Fant ingen minnepinne. Sett den inn og prøv igjen.")
            return
        self.downloading = True
        self.cancel.clear()
        self.button.configure(text="Stopp", fg_color="#b3261e", hover_color="#8c1d18")
        self.bar.set(0)
        self.status.configure(text="Ser etter nye videoer ...")
        threading.Thread(target=self.worker, args=(dest,), daemon=True).start()

    def worker(self, dest):
        try:
            n, ok = download_new_videos(dest, load_channels(), self.msgs.put, self.cancel)
            if self.cancel.is_set():
                text = f"Stoppet. {n} videoer ble lagret."
            elif not ok:
                text = f"Noe gikk galt. {n} videoer ble lagret. Prøv igjen senere."
            elif n == 0:
                text = "Ingen nye videoer denne gangen."
            else:
                text = f"Ferdig! {n} nye videoer lagret."
        except Exception:
            text = "Noe gikk galt. Sjekk internett og prøv igjen."
        self.msgs.put(("done", text))

    def poll(self):
        while not self.msgs.empty():
            kind, *rest = self.msgs.get_nowait()
            if kind == "status":
                self.status.configure(text=rest[0])
            elif kind == "progress":
                self.bar.set(rest[0])
            elif kind == "ready":
                self.button.configure(state="normal")
                self.status.configure(text="Trykk på knappen for å hente nye videoer.")
            elif kind == "done":
                self.downloading = False
                self.button.configure(
                    state="normal", text="Hent nye videoer", **self.button_colors
                )
                self.bar.set(0)
                self.status.configure(text=rest[0])
            elif kind == "quit":
                self.root.destroy()
                return
        self.root.after(150, self.poll)


if __name__ == "__main__":
    import customtkinter as ctk

    ctk.set_appearance_mode("dark")
    ctk.set_default_color_theme("blue")
    root = ctk.CTk()
    App(root)
    root.eval("tk::PlaceWindow . center")
    root.mainloop()
