"""Alex Videos: downloads new videos from fixed YouTube channels."""

import json
import os
import queue
import subprocess
import sys
import threading
import urllib.request

try:
    from _version import VERSION  # generated by the build job
except ImportError:
    VERSION = 0

GITHUB_REPO = "didriksg/alex-download"
CHANNELS_URL = f"https://raw.githubusercontent.com/{GITHUB_REPO}/main/channels.txt"
DEFAULT_CHANNELS = ["https://www.youtube.com/@AlexSkoog-ks1pl"]
FORMAT = "bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best"

FROZEN = getattr(sys, "frozen", False)
APP_DIR = os.path.dirname(sys.executable if FROZEN else os.path.abspath(__file__))


def load_channels():
    local = os.path.join(APP_DIR, "channels.txt")
    text = ""
    try:
        with urllib.request.urlopen(CHANNELS_URL, timeout=5) as r:
            text = r.read().decode("utf-8")
        if FROZEN:  # offline-fallback cache; skipped in dev to keep the repo copy pristine
            try:
                with open(local, "w", encoding="utf-8") as f:
                    f.write(text)
            except OSError:
                pass
    except Exception:
        try:
            with open(local, encoding="utf-8") as f:
                text = f.read()
        except OSError:
            pass
    urls = [s.strip() for s in text.splitlines() if s.strip() and not s.startswith("#")]
    return urls or DEFAULT_CHANNELS


DEST_FILE = os.path.join(APP_DIR, "folder.txt")


def load_dest():
    try:
        with open(DEST_FILE, encoding="utf-8") as f:
            p = f.read().strip()
        if p and os.path.isdir(p):
            return p
    except OSError:
        pass
    return os.path.join(os.path.expanduser("~"), "Videos")


def save_dest(p):
    try:
        with open(DEST_FILE, "w", encoding="utf-8") as f:
            f.write(p)
    except OSError:
        pass


def download_new_videos(dest_root, channels, event_cb):
    """Downloads new videos. Sends ("status", text)/("progress", 0..1) to
    event_cb. Returns (new_count, all_ok)."""
    import yt_dlp

    videos_dir = dest_root
    os.makedirs(videos_dir, exist_ok=True)
    done_ids = set()

    def hook(d):
        info = d.get("info_dict") or {}
        title = info.get("title") or ""
        if d["status"] == "downloading":
            event_cb(("status", f"Laster ned: {title}"))
            total = d.get("total_bytes") or d.get("total_bytes_estimate")
            if total:
                event_cb(("progress", d.get("downloaded_bytes", 0) / total))
        elif d["status"] == "finished":
            if info.get("id"):
                done_ids.add(info["id"])
            event_cb(("status", f"Behandler: {title} ..."))
            event_cb(("progress", 1.0))

    opts = {
        "format": FORMAT,
        "merge_output_format": "mp4",
        "outtmpl": os.path.join(videos_dir, "%(channel)s", "%(title)s.%(ext)s"),
        "download_archive": os.path.join(videos_dir, ".downloaded.txt"),
        "windowsfilenames": True,
        "ignoreerrors": True,
        "retries": 3,
        "quiet": True,
        "no_warnings": True,
        "noprogress": True,
        "progress_hooks": [hook],
    }
    if FROZEN:
        opts["ffmpeg_location"] = sys._MEIPASS
        opts["js_runtimes"] = {"deno": {"path": os.path.join(sys._MEIPASS, "deno.exe")}}

    with yt_dlp.YoutubeDL(opts) as ydl:
        retcode = ydl.download(channels)
    return len(done_ids), retcode == 0


def check_for_update(event_cb):
    """Swaps the running exe for the newest GitHub release. Returns new path or None."""
    if not FROZEN:
        return None
    exe = sys.executable
    try:
        os.remove(exe + ".old")
    except OSError:
        pass
    new = exe + ".new"
    try:
        url = f"https://api.github.com/repos/{GITHUB_REPO}/releases/latest"
        with urllib.request.urlopen(url, timeout=5) as r:
            rel = json.load(r)
        if int(rel["tag_name"].lstrip("v")) <= VERSION:
            return None
        asset = next(a for a in rel["assets"] if a["name"].endswith(".exe"))
        event_cb(("status", "Laster ned oppdatering ..."))

        def report(blocks, bs, total):
            if total > 0:
                event_cb(("progress", min(blocks * bs / total, 1.0)))

        urllib.request.urlretrieve(asset["browser_download_url"], new, report)
        os.rename(exe, exe + ".old")
        os.rename(new, exe)
        return exe
    except Exception:
        try:
            os.remove(new)
        except OSError:
            pass
        return None


class App:
    def __init__(self, root):
        self.root = root
        self.msgs = queue.Queue()
        self.dest = load_dest()
        root.title("Alex Videoer")
        root.geometry("520x360")
        root.resizable(False, False)
        if FROZEN:
            root.iconbitmap(os.path.join(sys._MEIPASS, "icon.ico"))

        ctk.CTkLabel(
            root, text="Alex sine videoer", font=ctk.CTkFont(size=28, weight="bold")
        ).pack(pady=(36, 4))
        ctk.CTkLabel(
            root,
            text="Henter nye videoer fra YouTube",
            font=ctk.CTkFont(size=13),
            text_color="gray60",
        ).pack(pady=(0, 24))
        self.button = ctk.CTkButton(
            root,
            text="Hent nye videoer",
            font=ctk.CTkFont(size=20, weight="bold"),
            height=56,
            corner_radius=28,
            command=self.start,
            state="disabled",
        )
        self.button.pack(fill="x", padx=56)
        self.bar = ctk.CTkProgressBar(root, height=8)
        self.bar.set(0)
        self.bar.pack(fill="x", padx=56, pady=(24, 10))
        self.status = ctk.CTkLabel(root, text="Starter ...", wraplength=440)
        self.status.pack(padx=24)

        bottom = ctk.CTkFrame(root, fg_color="transparent")
        bottom.pack(side="bottom", fill="x", pady=(0, 16))
        small = {
            "font": ctk.CTkFont(size=13),
            "height": 32,
            "fg_color": "gray25",
            "hover_color": "gray30",
        }
        row = ctk.CTkFrame(bottom, fg_color="transparent")
        row.pack()
        ctk.CTkButton(
            row, text="Åpne videomappen", command=self.open_folder, **small
        ).pack(side="left", padx=6)
        ctk.CTkButton(
            row, text="Velg mappe", command=self.choose_folder, **small
        ).pack(side="left", padx=6)
        root.after(150, self.poll)
        threading.Thread(target=self.update_worker, daemon=True).start()

    def update_worker(self):
        new_exe = check_for_update(self.msgs.put)
        if new_exe:
            self.msgs.put(("status", "Appen er oppdatert og starter på nytt ..."))
            subprocess.Popen([new_exe])
            self.msgs.put(("quit",))
        else:
            self.msgs.put(("ready",))

    def videos_folder(self):
        os.makedirs(self.dest, exist_ok=True)
        return self.dest

    def open_folder(self):
        folder = self.videos_folder()
        if sys.platform == "win32":
            os.startfile(folder)
        else:
            subprocess.run(["open", folder])

    def choose_folder(self):
        from tkinter import filedialog

        p = filedialog.askdirectory(
            initialdir=self.dest, title="Velg hvor videoene skal lagres"
        )
        if p:
            self.dest = os.path.normpath(p)
            save_dest(self.dest)

    def start(self):
        self.button.configure(state="disabled")
        self.bar.set(0)
        self.status.configure(text="Ser etter nye videoer ...")
        threading.Thread(target=self.worker, args=(self.dest,), daemon=True).start()

    def worker(self, dest):
        try:
            n, ok = download_new_videos(dest, load_channels(), self.msgs.put)
            if not ok:
                text = f"Noe gikk galt. {n} videoer ble lagret. Prøv igjen senere."
            elif n == 0:
                text = "Ingen nye videoer denne gangen."
            else:
                text = f"Ferdig! {n} nye videoer lagret."
        except Exception:
            text = "Noe gikk galt. Sjekk internett og prøv igjen."
        self.msgs.put(("done", text))

    def poll(self):
        while not self.msgs.empty():
            kind, *rest = self.msgs.get_nowait()
            if kind == "status":
                self.status.configure(text=rest[0])
            elif kind == "progress":
                self.bar.set(rest[0])
            elif kind == "ready":
                self.button.configure(state="normal")
                self.status.configure(text="Trykk på knappen for å hente nye videoer.")
            elif kind == "done":
                self.button.configure(state="normal")
                self.bar.set(0)
                self.status.configure(text=rest[0])
            elif kind == "quit":
                self.root.destroy()
                return
        self.root.after(150, self.poll)


if __name__ == "__main__":
    import customtkinter as ctk

    ctk.set_appearance_mode("dark")
    ctk.set_default_color_theme("blue")
    root = ctk.CTk()
    App(root)
    root.eval("tk::PlaceWindow . center")
    root.mainloop()
